apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
  - name: kube-proxy
    image: "{{hyperkube}}"
    command:
    - /hyperkube
    - proxy
    - --master=http://127.0.0.1:8080
    - --proxy-mode=iptables
    resources:
      requests:
        cpu: {{kube_proxy_requests_cpu}}
        memory: {{kube_proxy_requests_memory}}
      limits:
        cpu: {{kube_proxy_limits_cpu}}
        memory: {{kube_proxy_limits_memory}}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
