---
{% import "macros.j2" as _etcd with context %}
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: kube-apiserver
      image: "{{hyperkube}}"
      command:
        - /hyperkube
        - apiserver
        - --bind-address=0.0.0.0
        - --etcd-servers={{_etcd.peers()}}
        - --apiserver-count={{groups['kubernetes-masters']|length}}
        - --allow-privileged=true
        - --service-cluster-ip-range={{kubernetes_service_addresses}}
        - --secure-port={{kube_apiserver_secure_port}}
        - --advertise-address={{ansible_default_ipv4.address}}
        - --admission-control={{kube_admission_control}}
        - --runtime-config={{ kube_apiserver_runtime_config }}
{% if enable_external_admission_controller_webhook %}
        - --proxy-client-cert-file={{kube_cert_dir}}/client.pem
        - --proxy-client-key-file={{kube_cert_dir}}/client-key.pem
        - --requestheader-client-ca-file={{kube_cert_dir}}/client-ca.pem
{% endif %}
        - --tls-cert-file={{kube_cert_dir}}/apiserver.pem
        - --tls-private-key-file={{kube_cert_dir}}/apiserver-key.pem
        - --client-ca-file={{kube_cert_dir}}/ca.pem
        - --service-account-key-file={{kube_cert_dir}}/apiserver-key.pem
        - --token-auth-file=/etc/auth/tokens.csv
        - --authorization-mode={{kube_authorization_mode}}
        - --authorization-policy-file=/etc/auth/policies.jsonl
        - --storage-backend={{kube_storage_backend}}
{% if kube_enable_audit_logs %}
        - --audit-log-path={{kube_audit_log_path}}
        - --audit-log-maxsize={{kube_audit_log_maxsize}}
        - --audit-log-maxbackup={{kube_audit_log_maxbackup}}
{% endif %}
      resources:
        requests:
          cpu: {{kube_apiserver_requests_cpu}}
          memory: {{kube_apiserver_requests_memory}}
      livenessProbe:
        httpGet:
          host: 127.0.0.1
          port: 8080
          path: /healthz
        initialDelaySeconds: 15
        timeoutSeconds: 15
        periodSeconds: 15
      ports:
        - containerPort: {{kube_apiserver_secure_port}}
          hostPort: {{kube_apiserver_secure_port}}
          name: https
        - containerPort: 8080
          hostPort: 8080
          name: local
      volumeMounts:
        - mountPath: {{kube_cert_dir}}
          name: ssl-certs-kubernetes
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
        - mountPath: /etc/auth
          name: auth-kubernetes
          readOnly: true
  volumes:
    - hostPath:
        path: {{kube_cert_dir}}
      name: ssl-certs-kubernetes
    - hostPath:
        path: /usr/share/ca-certificates
      name: ssl-certs-host
    - hostPath:
        path: {{kube_auth_dir}}
      name: auth-kubernetes
